version: '3.7'
services:
  server:
    image: shmopen/code-push-server:latest
    container_name: codepush-server
    env_file:
      - .env
    volumes:
      - codepush-data-storage:/data/storage
      - codepush-data-tmp:/data/tmp
    environment:
      RDS_HOST: 'codepush-mysql'
      STORAGE_DIR: '/data/storage'
      DATA_DIR: '/data/tmp'
      NODE_ENV: 'production'
      REDIS_HOST: 'codepush-redis'
      VIRTUAL_HOST: 'codepush.glowvietnam.com'
      VIRTUAL_PORT: '33000'
      LETSENCRYPT_HOST: 'codepush.glowvietnam.com'
    ports:
      - '33000:3000'
    depends_on:
      - mysql
      - redis
    networks:
      - postgres
  mysql:
    image: mysql:latest
    container_name: codepush-mysql
    volumes:
      - codepush-data-mysql:/var/lib/mysql
      - ./sql/codepush-all-docker.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'On'
    networks:
      - postgres
  redis:
    image: redis:latest
    container_name: codepush-redis
    volumes:
      - codepush-data-redis:/data
    networks:
      - postgres

volumes:
  codepush-data-storage:
  codepush-data-tmp:
  codepush-data-mysql:
  codepush-data-redis:

networks:
  postgres:
    driver: bridge
    name: postgres